schema-version = "1.13.0"

[install]
# Dependencies for Ghost
nodejs_22.pkg-path = "nodejs_22"
nodejs_22.version = "22.23.1"
pnpm.pkg-path = "pnpm"
python314.pkg-path = "python314"
setuptools.pkg-path = "python314Packages.setuptools"

# Local development tools
git.pkg-path = "git"
git.outputs = "all"
just.pkg-path = "just"
just.outputs = "all"
markdownlint-cli.pkg-path = "markdownlint-cli"
parallel.pkg-path = "parallel"
parallel.outputs = "all"
pre-commit.pkg-path = "pre-commit"
pre-commit.outputs = "all"
prettier.pkg-path = "prettier"
taplo.pkg-path = "taplo"
yamllint.pkg-path = "yamllint"
yamllint.outputs = "all"
zizmor.pkg-path = "zizmor"

[vars]

[hook]
on-activate = '''
  # Setup a Python virtual environment

  export PYTHON_DIR="$FLOX_ENV_CACHE/python"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python -m venv "$PYTHON_DIR"
  fi
'''

[profile]
bash = '''
  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"
'''
zsh = '''
  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"
'''

[services]

[include]

[build]

[options]
